### ISSUE TITLE
Cannot clear screen / No colors

### ISSUE THREAD

**Issue by akashJx** [robiot/rustcat#34]
I really love this tool but this tool is missing a few features.
- I was able to clear screen with `Ctrl + L` with regular combination of `rlwrap` and `ncat`. I am not able to do the same with this. 
- There are no colors (with simple commands like `ls -la`. cannot highlight executables.)
- What's wrong with arrow keys
![image](https://user-images.githubusercontent.com/26841401/177534829-3c6803b7-b271-4ac7-b6b2-17e1a21bd7b5.png)

**Comment by robiot** [comment]
Try with the -H flag which enables "History". I would consider this a bad description of what it actually does. It makes arrows-, history- and command- completion work. A better, mire descriptive name for this feature would be "Interactive" since that basically is what it does. Now change your command to instead start with 'rcat -lHp'. This should theoretically work.

**Comment by akashJx** [comment]
With `-H` flag I am not having any issues. It works. Thanks.
Possible to add `Ctrl + L` to clear screen?

**Comment by robiot** [comment]
I am unsure. I'll see what I can do anyways.
